services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fin-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fin-network

  redis:
    image: redis:7-alpine
    container_name: fin-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fin-network

  producer:
    build:
      context: .
      dockerfile: apps/producer/Dockerfile
    container_name: fin-producer
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: notifications.exchange
      RABBITMQ_QUEUE: notifications.queue
      RABBITMQ_ROUTING_KEY: notifications.created
      RABBITMQ_DLX: notifications.dlx
      RABBITMQ_DLQ: notifications.dlq
      PRODUCER_PORT: 3000
      MAX_RETRY_ATTEMPTS: 3
      RETRY_DELAY_MS: 2000
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - fin-network
    restart: unless-stopped

  consumer:
    build:
      context: .
      dockerfile: apps/consumer/Dockerfile
    container_name: fin-consumer
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: notifications.exchange
      RABBITMQ_QUEUE: notifications.queue
      RABBITMQ_ROUTING_KEY: notifications.created
      RABBITMQ_DLX: notifications.dlx
      RABBITMQ_DLQ: notifications.dlq
      REDIS_URL: redis://redis:6379
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_DEFAULT_CHAT_ID: ${TELEGRAM_DEFAULT_CHAT_ID:-}
      MAX_RETRY_ATTEMPTS: 3
      RETRY_DELAY_MS: 2000
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - fin-network
    restart: unless-stopped

networks:
  fin-network:
    driver: bridge
